ProdOpcUa/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('opc.urls')),


]
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

opc/urls.py
from django.urls import path

from .views import *
from django.urls import include, path
from rest_framework import routers

# Dem Router das Viewset for den REST API bekannt geben
router = routers.DefaultRouter()
router.register(r'RegOpcUaServer', RegOpcUaServerViewSet)
router.register(r'Dienstleistungen', DienstleistungenViewSet)
router.register(r'Kunden', KundenViewSet)
router.register(r'Produkt', ProduktViewSet)
router.register(r'produktionsauftrag', ProduktAuftragViewSet)
router.register(r'Ressourcenplanung', RessourcenplanungViewSet)



#router.register(r'groups', views.GroupViewSet)

app_name = 'opc'
urlpatterns = [
    # wenn eine Anfrage an / reinkommt, dann übergebe das der Funktion
    # index aus der views.py
    path('', index, name='index'),

    # REST API einbinden
    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # Die Authentifizierung
    path("register", register, name="register"),
    path("logout", logout_request, name="logout"),
    path("login", login_request, name="login"),

    # Die Übersichtsseiten der Produktion und der Maschinen
    path('produktion', produktion, name='produktion'),
    path('maschinen', maschinen, name='maschinen'),

    # Die Unterseiten von Produktion und Maschinen
    # Maschinen werden durch OPC UA Server oder virtuelle OPC UA Server simuliert.
    # Die Dienstleistungen, also von den Maschinen ausführbare Arbeiten werden ins Produktionssystem aufgenommen
    # Damit werden dann die Produkte erstellt und die Produktionsaufträge überwacht und optimiert

    # Produktionsaufträge
    path('produktionsAuftrag', produktionsAuftragList.as_view(), name='produktionsAuftrag'),


    # Produkte
    path('produkte', produktList.as_view(), name='produkte'),

    # Von den Maschinen zur verfügung gestellte Dienstleistungen
    path('dienstleistungen', dienstleistungen_list, name='dienstleistungen'),

    # Die Maschienen werden durch OPC UA und virtuelle OPC Ua Server ersetzt

    # Die OPC UA Server
    path('regOpcUaServer', regOpcUaServer_list, name='regOpcUaServer'),


    # Produktionsauftrag erstellen
    path('produktionsAuftragErstellen', produktionsAuftragErstellen, name='produktionsAuftragErstellen'),

    # ProduktionsaÜberwachung
    path('produktionsUeberwachung',produktionsUeberwachung_list, name='produktionsUeberwachung'),
    #path('produktionsUeberwachung', prouktionsUeberwachung_list, name='produktionsUeberwachung'),

    # Ressourcenplanung, verteilen der Poduktionsaufträge auf die Maschinen
    path('ressourcenplanung', ressourcenplanungList.as_view(), name='ressourcenplanung'),

    # Anzeige der Kundendaten
    path('kunden', kundenList.as_view(), name='kunden'),

    # Die von den Serern eingehenden Daten
    path('serverdata',serverdataView.as_view(), name='serverdata'),




]

opc/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Formular für Registrierung
class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

opc/views.py
from django.shortcuts import render

# Create your views here.
from random import randint
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.db import models
from django.shortcuts import render, get_object_or_404
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect
from django import forms
from django.contrib.auth.models import User
from django.urls import reverse
from django.views import generic, View
from .forms import NewUserForm
from django.db.models import Count
from tablib import Dataset

from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib import messages
import json
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from rest_framework import viewsets
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .serializers import *

from .models import *

# Hauptseite
def index(request):
    return render(request=request,
                  template_name='main/index.html')

# Seite zum Registrieren
def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            login(request, user)
            return redirect("opc:index")

        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])

            return render(request=request,
                          template_name="main/register.html",
                          context={"form": form})

    form = UserCreationForm
    return render(request=request,
                  template_name="main/register.html",
                  context={"form": form})

# Abmeldung und Rückkehr zur Haauptseite
def logout_request(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect("opc:index")

# Anmeldung und Rückkehr zur Hauptseite
# Es wird ein Toast mit einer Nachricht ausgegeben
def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                messages.info(request, f"You are now logged in as {username}")
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request,
                  template_name="main/login.html",
                  context={"form": form})


# Erstellen der Übersichtseite für die Produktion
@login_required
def produktion(request):
    return render(request=request,
                  template_name='main/produktion.html')


# Erstellen der Übersichtseite für die Maschinen
@login_required
def maschinen(request):
    return render(request=request,
                  template_name='main/maschinen.html')


# Erstellen der Datenbankabfrage für die OpcUaServer
@login_required
def regOpcUaServer_list(request, template_name='main/opcregOpcUaServer.html'):
    regOpcUaServer = RegOpcUaServer.objects.all()

    data = {}
    data['object_list'] = regOpcUaServer

    return render(request, template_name, data)


# Erstellen der Datenbankabfrage für Dienstleistungen
@login_required
def dienstleistungen_list(request, template_name='main/opcdienstleistungen.html'):
    dienstleistungen = Dienstleistungen.objects.all()

    data = {}
    data['object_list'] = dienstleistungen

    return render(request, template_name, data)



# Erstellen der Datenbankabfrage für die Produkte


class  produktList(ListView):
    template_name='main/opcprodukt.html'
    Model = Produkt
    def get_queryset(self):
        return Produkt.objects.all()



# Erstellen der Datenbankabfrage für die Kunden
@method_decorator(login_required, name='dispatch')
class kundenList(ListView):
    template_name='main/opckunden.html'
    Model = Kunden
    def get_queryset(self):
        return Kunden.objects.all()



# Erstellen der Datenbankabfrage für ProduktionsAuftrag
@method_decorator(login_required, name='dispatch')
class produktionsAuftragList(ListView):
    template_name='main/opcproduktionsAuftrag.html'
    Model = ProduktionsAuftrag
    def get_queryset(self):
        return ProduktionsAuftrag.objects.all()


# Erstellen der Datenbankabfrage für die Ressourcenplannung
@method_decorator(login_required, name='dispatch')
class ressourcenplanungList(ListView):
    template_name='main/opcressourcen.html'
    def get_queryset(self):
        return Ressourcenplanung.objects.all()



# Erstellen der Ansicht der serverdaten
@method_decorator(login_required, name='dispatch')
class serverdataView(ListView):
    template_name='main/serverdata.html'
    Model = Serverdata

    def get_queryset(self):
        return Serverdata.objects.all()





# Erstellen von Produktionsaufträgen
@login_required
def produktionsAuftragErstellen(request):
    return render(request=request,
                  template_name='main/opcproduktionsAuftragErstellen.html')


# Produktionsüberwachung
@login_required
def produktionsUeberwachung_list(request, template_name='main/opcproduktionsUeberwachung.html'):
    produktionsAuftrag = ProduktionsAuftrag.objects.all().order_by('auftragseingang', 'auftragsstatus',)
    anzahlauftraege = ProduktionsAuftrag.objects.count()

    wochentage = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
    auslastung = [80, 70, 90, 80, 70, 60, 60],
    #auftragszeiten = Produkt.objects.all().aggregate(Count('erstellungszeit'))
    auftragszeiten = Produkt.objects.all()
    anzahlserver = RegOpcUaServer.objects.count()
    anzahlprodukte = Produkt.objects.count()

    produkt = [obj.produkt for obj in produktionsAuftrag]
    auftragsmenge = [int(obj.auftragsmenge) for obj in produktionsAuftrag]

    maschinetime = anzahlserver * timedelta(days=1)

    context = {
        'produkt': produkt,
        'auftragsmenge': auftragsmenge,
        'produktionsAuftrag': produktionsAuftrag,
        'auftragszeiten': auftragszeiten,
        'anzahlauftraege': anzahlauftraege,
        'anzahlserver': anzahlserver,
        'wochentage': wochentage,
        'auslastung': auslastung,
        'maschinetime': maschinetime,
        'anzahlprodukte': anzahlprodukte,
        'list_produktionsAuftrag':produktionsAuftrag,
    }


    return render(request, template_name, context)







#Für REST API zum export und Import der Daten

class RegOpcUaServerViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = RegOpcUaServer.objects.all()
    serializer_class = RegOpcUaServerSerializer

class DienstleistungenViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Dienstleistungen.objects.all()
    serializer_class = DienstleistungenSerializer

class KundenViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Kunden.objects.all()
    serializer_class = KundenSerializer


class ProduktViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Produkt.objects.all()
    serializer_class = ProduktSerializer

class ProduktAuftragViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = ProduktionsAuftrag.objects.all()
    serializer_class = ProduktionsAuftragSerializer

class RessourcenplanungViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Ressourcenplanung.objects.all()
    serializer_class = RessourcenplanungSerializer

opc/templates/main/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}

        <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>



    <style type=”text/css”></style>
    <!-- Prism CSS -->
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
</head>


<body>
  {% load static %}
    {% load bootstrap4 %}

   <nav class="nav-extended"  >
    <div class="nav-wrapper blue darken-3 " >
      <a href="#" class="brand-logo">SmartParts AG </a>

    </div>

  </nav>




{% block content %}
<h1>{{ titel }}</h1>
<p class="lead">
  Herzlich willkommen auf der Seite! Hier k&ouml;nnt Ihr euch einfach anmelden!
  Bitte schlie&szlig;t diese Seite nicht!
</p>
<hr />





 <div class="row">
    <div class="col s12 m10">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Anmeldung</span>
          <p>Bitte melden Sie sich hier an</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:register' %}" class="btn btn-danger" >Registrieren</a>
          <a href="{% url 'opc:login' %}" class="btn btn-danger">Login</a>
        </div>
      </div>
    </div>
  </div>
<div class="row">
    <div class="col s12 m10">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Produktion</span>
          <p> Hier gehts zur Produktion und Auftragsübersicht</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:produktion' %}" class="btn btn-danger" > Weiter</a>

        </div>
      </div>
    </div>
  </div>
<div class="row">
    <div class="col s12 m10">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Maschinen </span>
          <p> Hier gehts zu den verfügbaren Maschinen</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:maschinen' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>
  </div>


{% endblock %}

</body>



<!-- Prism JS -->
<script src="{% static 'tinymce/js/prism.js' %}"></script>
</html>

opc/templates/main/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% extends 'main/includes/header.html' %}

class NewUserForm(UserCreationForm):

{% block content %}

    <div class="container">
        <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info orange darken-4" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/opcregister" target="blank"><strong>register here</strong></a>!
    </div>
{% endblock %}

</body>
</html>

opc/templates/main/maschinen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OPC Ua Netzwerk Details</title>
</head>
<body>
{% extends 'main/includes/header.html' %}
{% block content %}


<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Dienstleistungen  der OPC UA Server (Maschinen)  </span>
          <p> Hier gehts zu den verfügbaren Dienstleistungen  registrierte OPC UA (Raspery)</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:dienstleistungen' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>


    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Dienstleistungen  der OPC UA Server erstellen </span>
          <p> Hier gehts zu den verfügbaren Maschinen</p>

        </div>
        <div class="card-action">
          <a href="{% url 'admin:opc_dienstleistungen_add' %}"  class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>
  </div>
    <div class="row">
        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">OPC UA Server anzeigen</span>
              <p>Hier gehts zu den registrierten OPC Ua Servern</p>

            </div>
            <div class="card-action">
              <a href="{% url 'opc:regOpcUaServer' %}" class="btn btn-danger" >Weiter</a>

            </div>
          </div>
        </div>

        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">OPC UA Server hinzufügen</span>
              <p> Hier gehts zur Produktion und Auftragsübersicht</p>

            </div>
            <div class="card-action">
              <a href="{% url 'admin:opc_regopcuaserver_add' %}" class="btn btn-danger" > Weiter</a>

            </div>
          </div>
        </div>
      </div>

    <div class="row">
        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title"> Serverdaten </span>
              <p> Hier gehts zu den Serverdaten</p>

            </div>
            <div class="card-action">
              <a href="{% url 'opc:serverdata' %}" class="btn btn-danger" >Weiter</a>
            </div>
          </div>
        </div>
        <div class="col s6 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">Überischt Smartparts AG</span>
              <p> Hier gehts zur Übersicht </p>

            </div>
            <div class="card-action">
              <a href="{% url 'admin:index' %}" class="btn btn-danger" > Weiter</a>

            </div>
          </div>
        </div>
      </div>




{% endblock %}
</body>

</html>

opc/templates/main/opcproduktionsUeberwachung.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produktionsuebersicht</title>
</head>
<body>

</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ProduktionsAuftrag</title>
<link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">

</head>
<body id="page-top">
{% extends 'main/includes/header2.html' %}
{% block content %}



    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">




        <!-- Begin Page Content -->
        <div class="container-fluid">



          <div class="row">
            <div class="col s3 m3">
              <div class="card white">
                <div class="card-content black-text">

                  <span class="card-title"> Anazahl Server </span>


                  <p> {{anzahlserver}}</p>


                </div>
                <div class="card-action">
                  <a href="{% url 'opc:regOpcUaServer' %}" class="btn btn-danger" >Zu den Servern</a>

                </div>
              </div>
            </div>
            <div class="col s3 m3">
              <div class="card white">
                <div class="card-content ">
                  <span class="card-title"> Anzahl Aufträge </span>
                  <p> {{anzahlauftraege}} </p>

                </div>
                <div class="card-action">
                  <a href="{% url 'opc:produktionsAuftrag' %}"  class="btn btn-danger" >Zu den Aufrtägen</a>

                </div>
              </div>
            </div>

            <div class="col s3 m3">
              <div class="card white">
                <div class="card-content ">
                  <span class="card-title">  Anzahl Produkte</span>
                  <p> {{anzahlprodukte}}</p>

                </div>
                <div class="card-action">
                  <a href="{% url 'opc:produkte' %}"  class="btn btn-danger" >Zu den Produkten</a>

                </div>
              </div>
            </div>

          </div>




          <!-- Content Row -->

          <div class="row">

            <!-- Area Chart -->
            <div class="col-xl-12 col-lg-7">
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Kapazitätsauslastung</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Dropdown Header:</div>
                      <a class="dropdown-item" href="#">Action</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                  </div>
                </div>
              </div>
            </div>

            
          </div>







          <!-- Content Row -->
          <div class="row">

            <!-- Content Column -->
            <div class="col-lg-12 mb-4">



          <!-- DataTales Example -->
          <div class="card shadow mb-4">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold text-primary">Aufträge</h6>
            </div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>

                    <tr>

                      <th scope="col">Auftragsnummer</th>
                      <th scope="col">Kundennummer</th>
                      <th scope="col">Produkt</th>
                      <th scope="col">Auftragsmenge</th>
                      <th scope="col">AktuellerSchritt</th>
                      <th scope="col">Auftragsstatus</th>
                      <th scope="col">Auftragseingang</th>
                      <th scope="col">Fortschritt</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for produktionsAuftrag in list_produktionsAuftrag %}
                   <tr>

                       <td>{{ produktionsAuftrag.auftragsnummer}}</td>
                       <td>{{ produktionsAuftrag.kunde}}</td>
                       <td>{{ produktionsAuftrag.produkt}}</td>
                       <td>{{ produktionsAuftrag.auftragsmenge}}</td>

                       <td>{{ produktionsAuftrag.aktuellerSchritt}}</td>
                       <td>{{ produktionsAuftrag.auftragsstatus}}</td>
                       <td>{{ produktionsAuftrag.auftragseingang}}</td>
                       <td>{{ produktionsAuftrag.fortschritt}}</td>



                    </tr>

                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          </div>
          </div>


          </div>

  <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Pankraz Schmitt 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

      </div>
      <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

{% endblock %}
{% block scripts %}
<script>
</script>
{% endblock %}

<script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>
</body>
</html>

opc/templates/main/produktion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produktion</title>



</head>
<body>
{% extends 'main/includes/header.html' %}


{% block content %}
 <!-- Project Card Example -->


<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Produktionsüberwachung </span>
          <p> Hier gehts zur Produktionsüberwachung</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:produktionsUeberwachung' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>

    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
         <div class="card-content white-text">
              <span class="card-title">Überischt Smartparts AG</span>
              <p> Hier gehts zur Übersicht </p>

            </div>
            <div class="card-action">
              <a href="{% url 'admin:index' %}" class="btn btn-danger" > Weiter</a>

            </div>




      </div>
    </div>
  </div>
<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Auftragsübersicht </span>
          <p> Hier gehts zu den Aufträgen</p>

        </div>
        <div class="card-action">
          <a href="{% url 'opc:produktionsAuftrag' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>

    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Auftrag erstellen </span>
          <p> Hier können Sie Aufträge erstellen</p>

        </div>
        <div class="card-action">
          <a href="{% url 'admin:opc_produktionsauftrag_add' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>
  </div>

<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Produkte</span>
          <p> Hier gehts zu den Produkten</p>

        </div>
        <div class="card-action">

          <a href="{% url 'opc:produkte' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>

    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Produkte ertellen </span>
          <p> Hier können Sie Produkte erstellen</p>

        </div>
         <div class="card-action">

          <a href="{% url 'admin:opc_produkt_add' %}" class="btn btn-danger" >Weiter</a>


        </div>
      </div>
    </div>
  </div>

<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Kunden </span>
          <p> Hier gehts zu den Kunden</p>

        </div>
         <div class="card-action">
             <a href="{% url 'opc:kunden' %}"  class="btn btn-danger" >Weiter</a>


        </div>
      </div>
    </div>

    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> Kunden registrieren </span>
          <p> Hier können neue Kunden registriert werden </p>

        </div>
        <div class="card-action">

            <a href="{% url 'admin:opc_kunden_add' %}" class="btn btn-danger" >Weiter</a>

        </div>
      </div>
    </div>
  </div>

<div class="row">
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
         <div class="card-content white-text">
          <span class="card-title"> Ressourcenplanung </span>
          <p> Hier können Sie neue Einsatzpläne erstellen  </p>

        </div>
        <div class="card-action">
          <a href="{% url 'admin:opc_ressourcenplanung_add' %}"  class="btn btn-danger" >Weiter</a>

        </div>


      </div>
    </div>
</div>




{% endblock %}
</body>

</html>

opc/templates/main/register.html
<!DOCTYPE html>
<html lang="en" xmlns:color="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
{% extends 'main/includes/header.html' %}

{% block content %}

    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-outline-info orange darken-4 " type="submit">Sign Up</button>
    </form>

    If you already have an account <a href="/login" target="blank"><strong>login</strong></a> instead.

{% endblock %}
</body>
</html>